version: 2
jobs:
  test_node_8:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - npm test

  test_node_9:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - run: npm install
      - npm test

  test_node_10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - npm test

  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run-script build
      - run: npx run-script deploy

workflows:
  version: 2
  test_and_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    jobs:
      - test_node_8
      - test_node_9
      - test_node_10
      - release:
          requires:
            - test_node_8
            - test_node_9
            - test_node_10
